name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 3.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils: ^4.6.22
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0

  # Media
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6
  file_picker: ^4.6.1
  just_audio: ^0.9.29
  syncfusion_flutter_pdfviewer: ^20.3.50
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.0

  # APIs
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0

  flutter_html: ^2.2.1
  google_mobile_ads: ^1.3.0

  # State Management Technique
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4

  # Share
  share_plus: ^4.0.10
  flutter_custom_tabs: ^1.0.4

  # Firebase
  firebase_crashlytics: ^3.0.1
  firebase_core: 2.1.0
  firebase_auth: 4.0.1
  firebase_messaging: 14.0.1


  # AUTHENTICATION
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1

  # Remote Notification
  onesignal_flutter: 3.4.1

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.1
  flutter_svg: ^0.22.0 
  lottie: ^1.4.3

  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.12
  get_it: ^7.2.0
  pinput: ^2.2.21
  flutter_secure_storage: ^7.0.1
  shimmer: ^2.0.0
  video_thumbnail_imageview: ^0.0.5
  flash: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs


dependency_overrides:
  firebase_core_platform_interface: 4.5.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 100
        - asset: fonts/Poppins-regular.ttf
          weight: 400
        - asset: fonts/Poppins-Bold.ttf
          weight: 600

